
import nuke  
import os

from PysideImport import *


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(Qt.NonModal)
        Form.resize(397, 421)
        icon = QIcon()
        icon.addPixmap(QPixmap(os.path.dirname(__file__)+"/icons/icon.png"), QIcon.Normal, QIcon.Off)
        Form.setWindowIcon(icon)
        self.verticalLayout_7 = QVBoxLayout(Form)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_2 = QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_settings4 = QGroupBox(Form)
        self.groupBox_settings4.setObjectName("groupBox_settings4")
        self.horizontalLayout_9 = QHBoxLayout(self.groupBox_settings4)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_8 = QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_3 = QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_4 = QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(30, -1, 20, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.checkBox_shake_effect = QCheckBox(self.groupBox_settings4)
        font = QFont()
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_shake_effect.setFont(font)
        self.checkBox_shake_effect.setChecked(False)
        self.checkBox_shake_effect.setObjectName("checkBox_shake_effect")
        self.verticalLayout_4.addWidget(self.checkBox_shake_effect)
        self.checkBox_zoom_effect = QCheckBox(self.groupBox_settings4)
        font = QFont()
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_zoom_effect.setFont(font)
        self.checkBox_zoom_effect.setChecked(True)
        self.checkBox_zoom_effect.setObjectName("checkBox_zoom_effect")
        self.verticalLayout_4.addWidget(self.checkBox_zoom_effect)
        self.horizontalLayout_4 = QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QLabel(self.groupBox_settings4)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.lineEdit_shortcut = QLineEdit(self.groupBox_settings4)
        self.lineEdit_shortcut.setMaximumSize(QSize(150, 16777215))
        self.lineEdit_shortcut.setObjectName("lineEdit_shortcut")
        self.horizontalLayout_4.addWidget(self.lineEdit_shortcut)
        self.horizontalLayout_4.setStretch(0, 2)
        self.horizontalLayout_4.setStretch(1, 8)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(20, -1, 20, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_icon = QLabel(self.groupBox_settings4)
        self.label_icon.setText("")
        self.label_icon.setPixmap(QPixmap(os.path.dirname(__file__)+"/icons/icon.png"))
        self.label_icon.setObjectName("label_icon")
        self.verticalLayout_3.addWidget(self.label_icon)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_8.addLayout(self.horizontalLayout_3)
        self.pushButton_documentation = QPushButton(self.groupBox_settings4)
        self.pushButton_documentation.setObjectName("pushButton_documentation")
        self.verticalLayout_8.addWidget(self.pushButton_documentation)
        self.horizontalLayout_9.addLayout(self.verticalLayout_8)
        self.verticalLayout_2.addWidget(self.groupBox_settings4)
        self.groupBox_status = QGroupBox(Form)
        self.groupBox_status.setObjectName("groupBox_status")
        self.verticalLayout_6 = QVBoxLayout(self.groupBox_status)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_5 = QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(20, -1, 15, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QLabel(self.groupBox_status)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.label_4 = QLabel(self.groupBox_status)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.label_5 = QLabel(self.groupBox_status)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.label_2 = QLabel(self.groupBox_status)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.line = QFrame(self.groupBox_status)
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_5.addWidget(self.line)
        self.label_6 = QLabel(self.groupBox_status)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.label_icon_2 = QLabel(self.groupBox_status)
        self.label_icon_2.setFrameShape(QFrame.NoFrame)
        self.label_icon_2.setText("")
        self.label_icon_2.setPixmap(QPixmap(os.path.dirname(__file__)+"/icons/mouse.png"))
        self.label_icon_2.setObjectName("label_icon_2")
        self.horizontalLayout.addWidget(self.label_icon_2)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addWidget(self.groupBox_status)
        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_plugins_version = QLabel(Form)
        self.label_plugins_version.setObjectName("label_plugins_version")
        self.horizontalLayout_2.addWidget(self.label_plugins_version)
        spacerItem = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout = QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_8 = QLabel(Form)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.label_9 = QLabel(Form)
        self.label_9.setAlignment(Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_2.setStretch(0, 3)
        self.horizontalLayout_2.setStretch(1, 28)
        self.horizontalLayout_2.setStretch(2, 3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.setStretch(0, 4)
        self.verticalLayout_2.setStretch(1, 4)
        self.verticalLayout_2.setStretch(2, 1)
        self.verticalLayout_7.addLayout(self.verticalLayout_2)

        self.retranslateUi(Form)
        QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Km NodeGraph Easy Navigate"))
        self.groupBox_settings4.setTitle(_translate("Form", "Settings"))
        self.checkBox_shake_effect.setText(_translate("Form", "Shake Effect"))
        self.checkBox_zoom_effect.setText(_translate("Form", "Zoom Effect"))
        self.label_3.setText(_translate("Form", "Shortcut :"))
        self.lineEdit_shortcut.setText(_translate("Form", "shift+e"))
        self.pushButton_documentation.setText(_translate("Form", "Apply"))
        self.groupBox_status.setTitle(_translate("Form", "Help"))
        self.label.setText(_translate("Form", "Left Button    :    Jump to Bookmark"))
        self.label_4.setText(_translate("Form", "                         Assign New Bookmark"))
        self.label_5.setText(_translate("Form", "Middle Button :   Edit"))
        self.label_2.setText(_translate("Form", "Right Button  :    Remove"))
        self.label_6.setText(_translate("Form", "Assign Bookmark : Select a node or backdrop, Then click on an empty bookmark to assign"))
        self.label_plugins_version.setText(_translate("Form", "Km NodeGraph Easy Navigate v1.1"))
        self.label_8.setText(_translate("Form", "By Hossein Karamian"))
        self.label_9.setText(_translate("Form", "www.kmworks.ir"))

